# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: cassassi <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/03/21 11:18:06 by cassassi          #+#    #+#              #
#    Updated: 2022/03/21 11:18:10 by cassassi         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME	=	megaphone

SRC		=	megaphone.cpp

FLAG	=	-std=c++98 -Wall -Wextra -Werror

CC		=	c++

all		:	$(NAME)

$(NAME)	:	
			$(CC) -o $(NAME) $(FLAG) $(SRC)

clean	:	
			rm -rf $(NAME)


re		:	clean all
