NAME	=	phonebook

SRC		=	PhoneBook.cpp Contact.cpp main.cpp

FLAG	=	-std=c++98 -Wall -Wextra -Werror

CC		=	c++

all		:	$(NAME)

$(NAME)	:	
			$(CC) -o $(NAME) $(FLAG) $(SRC)

clean	:	
			rm -rf $(NAME)


re		:	clean all